-- MySQL Script generated by MySQL Workbench
-- Tue May  7 12:23:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`conta__corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta__corrente` (
  `idconta__corrente` INT NOT NULL AUTO_INCREMENT,
  `saldo` INT NULL,
  PRIMARY KEY (`idconta__corrente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco` (
  `idbanco1` INT NOT NULL,
  PRIMARY KEY (`idbanco1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta__poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta__poupanca` (
  `idconta__corrente` INT NOT NULL AUTO_INCREMENT,
  `saldo` INT NULL,
  PRIMARY KEY (`idconta__corrente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idconta__corrente` INT NOT NULL,
  `banco_idbanco1` INT NOT NULL,
  `idconta__poupanca` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `idconta__corrente`, `banco_idbanco1`),
  INDEX `fk_cliente2_conta__corrente_idx` (`idconta__corrente` ASC) VISIBLE,
  INDEX `fk_cliente_banco1_idx` (`banco_idbanco1` ASC) VISIBLE,
  INDEX `fk_cliente_conta__poupanca1_idx` (`idconta__poupanca` ASC) VISIBLE,
  CONSTRAINT `fk_cliente2_conta__corrente`
    FOREIGN KEY (`idconta__corrente`)
    REFERENCES `mydb`.`conta__corrente` (`idconta__corrente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_banco1`
    FOREIGN KEY (`banco_idbanco1`)
    REFERENCES `mydb`.`banco` (`idbanco1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_conta__poupanca1`
    FOREIGN KEY (`idconta__poupanca`)
    REFERENCES `mydb`.`conta__poupanca` (`idconta__corrente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
